<a href="https://colab.research.google.com/github/VSah7079/aiml_workshop_test/blob/main/AI_ML_Workshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy-Numerical Python

Advantages of Numpy Arrays:
1.Allows sever

In [ ]:
import numpy as np

In [ ]:
np_array= np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
np_array.shape

(5,)

In [ ]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])


In [ ]:
x=np.zeros((4,10))

In [ ]:
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
y=np.ones((6,7))
print(y)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
eye=np.eye(4)
eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
randomval=np.random.random((3,4))
randomval

array([[0.08531889, 0.20204771, 0.19681373, 0.79679659],
       [0.06255702, 0.38924647, 0.12541872, 0.11544704],
       [0.72176281, 0.81945505, 0.05987618, 0.042818  ]])

In [ ]:
line_space=np.linspace(10,100,23)
line_space

array([ 10.        ,  14.09090909,  18.18181818,  22.27272727,
        26.36363636,  30.45454545,  34.54545455,  38.63636364,
        42.72727273,  46.81818182,  50.90909091,  55.        ,
        59.09090909,  63.18181818,  67.27272727,  71.36363636,
        75.45454545,  79.54545455,  83.63636364,  87.72727273,
        91.81818182,  95.90909091, 100.        ])

In [ ]:
list=[1,2,3,4,5,6,7,8,]
list

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
converted_list=np.asarray(list)
converted_list

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
first =np.random.randint(0,10,(3,3))
second=np.random.randint(10,20,(3,3))
print(first)





[[2 0 8]
 [4 8 0]
 [8 9 7]]


In [ ]:
print(second)

[[17 14 18]
 [10 19 18]
 [12 18 15]]


In [ ]:
print(np.add(first,second))

[[19 14 26]
 [14 27 18]
 [20 27 22]]


In [ ]:
print(np.subtract(first,second))

[[-15 -14 -10]
 [ -6 -11 -18]
 [ -4  -9  -8]]


In [ ]:
print(np.multiply(first,second))

[[ 34   0 144]
 [ 40 152   0]
 [ 96 162 105]]


In [ ]:
print(np.divide(first,second))

[[0.11764706 0.         0.44444444]
 [0.4        0.42105263 0.        ]
 [0.66666667 0.5        0.46666667]]


In [ ]:
trans=np.transpose(first)
print(trans)

[[2 4 8]
 [0 8 9]
 [8 0 7]]


In [ ]:
print(np.dot(first,second))

[[130 172 156]
 [148 208 216]
 [310 409 411]]


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.datasets import load_boston


In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import numpy as np

In [ ]:
import  numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split


In [ ]:
from sklearn.preprocessing import LabelEncoder
